theme: jekyll-theme-minimal
title: MiniBails's homepage
description: Bookmark this to keep an eye on my project updates!
plugins:
  - jekyll-include-cache
include:
  - assets/css/custom.css
  - _includes/head-custom.html